import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const PAGE_W = 210, PAGE_H = 297, MARGIN = 14;
const CONTENT_W = PAGE_W - MARGIN * 2;

const C = {
  bg: [10,15,30], surface: [18,27,50], border: [37,52,85],
  primary: [99,102,241], primaryDark: [67,56,202],
  white: [255,255,255], slate100: [241,245,249],
  slate300: [148,163,184], slate400: [100,116,139], slate500: [71,85,105],
  red: [239,68,68], redBg: [69,10,10],
  amber: [245,158,11], amberBg: [69,39,3],
  green: [16,185,129], greenBg: [6,55,32],
};

const fillPage = (doc) => { doc.setFillColor(...C.bg); doc.rect(0,0,PAGE_W,PAGE_H,'F'); };
const addPage  = (doc) => { doc.addPage(); fillPage(doc); };

const set = (doc, size, style, color) => {
  doc.setFontSize(size); doc.setFont('helvetica', style || 'normal'); doc.setTextColor(...(color || C.white));
};

const footer = (doc, n, total) => {
  const y = PAGE_H - 8;
  set(doc, 7, 'normal', C.slate500);
  doc.text('Generated by LexAudit  |  AI-generated analysis — not legal advice', MARGIN, y);
  doc.text(`Page ${n} of ${total}`, PAGE_W - MARGIN, y, { align: 'right' });
  doc.setDrawColor(...C.border); doc.setLineWidth(0.3);
  doc.line(MARGIN, y - 3, PAGE_W - MARGIN, y - 3);
};

const sectionHeading = (doc, text, y) => {
  doc.setFillColor(...C.primary); doc.rect(MARGIN, y, 3, 6, 'F');
  set(doc, 13, 'bold', C.white); doc.text(text, MARGIN + 6, y + 4.5);
  return y + 12;
};

const riskColor = (level) => level === 'High' ? C.red : level === 'Medium' ? C.amber : C.green;

const textBlock = (doc, text, x, y, maxW, lh = 4.5) => {
  if (!text) return y;
  const lines = doc.splitTextToSize(String(text), maxW);
  doc.text(lines, x, y);
  return y + lines.length * lh;
};

// Cover page
const buildCover = (doc, comparison) => {
  fillPage(doc);
  doc.setFillColor(...C.primaryDark); doc.rect(0,0,PAGE_W,70,'F');
  doc.setFillColor(...C.primary);     doc.rect(0,60,PAGE_W,12,'F');

  set(doc, 28, 'bold', C.white);
  doc.text('Lex', MARGIN, 32);
  set(doc, 28, 'bold', [167,170,255]);
  doc.text('Audit', MARGIN + doc.getTextWidth('Lex'), 32);
  set(doc, 9, 'normal', [199,210,254]);
  doc.text('Contract Comparison Report', MARGIN, 42);
  set(doc, 18, 'bold', C.white);
  doc.text('CONTRACT COMPARISON', MARGIN, 57);

  let y = 80;
  // Contract A vs B
  const half = CONTENT_W / 2 - 3;
  [[comparison.contractA,'A'],[comparison.contractB,'B']].forEach(([c, lbl], i) => {
    const x = MARGIN + i * (half + 6);
    doc.setFillColor(...C.surface); doc.setDrawColor(...C.border); doc.setLineWidth(0.3);
    doc.roundedRect(x, y, half, 38, 2, 2, 'FD');
    set(doc, 7, 'bold', C.slate400); doc.text(`CONTRACT ${lbl}`, x + 5, y + 7);
    const nameLines = doc.splitTextToSize(c.fileName || 'Untitled', half - 10);
    set(doc, 9, 'bold', C.white); doc.text(nameLines, x + 5, y + 13);
    set(doc, 7, 'normal', C.slate400);
    doc.text(new Date(c.createdAt).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric'}), x + 5, y + 22);
    const rc = riskColor(c.riskLevel);
    set(doc, 20, 'bold', rc); doc.text(String(c.riskScore ?? 0), x + 5, y + 33);
    set(doc, 7, 'normal', C.slate400); doc.text(`/ 100  ${c.riskLevel} Risk`, x + 5 + doc.getTextWidth(String(c.riskScore ?? 0)) + 2, y + 33);
  });
  y += 44;

  // Stats row
  const { stats } = comparison;
  const delta = stats.scoreB - stats.scoreA;
  const deltaColor = delta > 0 ? C.red : delta < 0 ? C.green : C.slate400;
  const statItems = [
    { label: 'Risk Delta',    value: (delta > 0 ? '+' : '') + delta, color: deltaColor },
    { label: 'Added',         value: `+${stats.added}`,   color: C.green },
    { label: 'Removed',       value: `-${stats.removed}`, color: C.red   },
    { label: 'Modified',      value: `~${stats.modified}`, color: C.amber },
    { label: 'Unchanged',     value: stats.unchanged,     color: C.slate400 },
  ];
  const sw = CONTENT_W / statItems.length;
  statItems.forEach((s, i) => {
    const x = MARGIN + i * sw;
    doc.setFillColor(...C.surface); doc.setDrawColor(...C.border); doc.setLineWidth(0.3);
    doc.roundedRect(x, y, sw - 2, 18, 2, 2, 'FD');
    set(doc, 14, 'bold', s.color); doc.text(String(s.value), x + (sw/2)-1, y+11, {align:'center'});
    set(doc, 6.5, 'normal', C.slate400); doc.text(s.label, x + (sw/2)-1, y+16, {align:'center'});
  });
  y += 24;

  // Verdict
  if (comparison.aiSummary?.overallVerdict) {
    doc.setFillColor(...C.surface); doc.setDrawColor(...C.primary); doc.setLineWidth(0.5);
    doc.roundedRect(MARGIN, y, CONTENT_W, 14, 2, 2, 'FD');
    set(doc, 7, 'bold', C.slate400); doc.text('OVERALL VERDICT', MARGIN+5, y+6);
    set(doc, 10, 'bold', C.primary);  doc.text(comparison.aiSummary.overallVerdict, MARGIN+5, y+12);
    y += 18;
  }

  // Disclaimer
  y = PAGE_H - 22;
  doc.setDrawColor(...C.border); doc.setLineWidth(0.3); doc.line(MARGIN,y,PAGE_W-MARGIN,y);
  set(doc, 7, 'normal', C.slate500);
  doc.text('This comparison is AI-generated and should not be considered legal advice.', MARGIN, y+5);
  doc.text('Consult a qualified attorney before making any legal decisions.', MARGIN, y+9);
};

// AI Summary page
const buildAISummary = (doc, comparison) => {
  addPage(doc);
  let y = MARGIN;
  y = sectionHeading(doc, 'AI Comparison Summary', y);

  const ai = comparison.aiSummary;
  if (!ai) { set(doc, 9, 'normal', C.slate400); doc.text('No AI summary available.', MARGIN, y); return; }

  if (ai.summary) {
    doc.setFillColor(...C.surface); doc.setDrawColor(...C.border); doc.setLineWidth(0.3);
    const summLines = doc.splitTextToSize(ai.summary, CONTENT_W - 10);
    const boxH = 10 + summLines.length * 4.2;
    doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 2, 2, 'FD');
    set(doc, 7, 'bold', C.primary); doc.text('SUMMARY', MARGIN+5, y+5);
    set(doc, 8.5, 'normal', C.slate100); doc.text(summLines, MARGIN+5, y+10);
    y += boxH + 5;
  }

  if (ai.recommendation) {
    const recLines = doc.splitTextToSize(ai.recommendation, CONTENT_W - 10);
    const boxH = 10 + recLines.length * 4.2;
    doc.setFillColor(20,30,70); doc.setDrawColor(...C.primary); doc.setLineWidth(0.4);
    doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 2, 2, 'FD');
    set(doc, 7, 'bold', C.primary); doc.text('RECOMMENDATION', MARGIN+5, y+5);
    set(doc, 8.5, 'normal', C.white); doc.text(recLines, MARGIN+5, y+10);
    y += boxH + 5;
  }

  const sections = [
    { label: 'Major Differences',       items: ai.majorDifferences || [],       color: C.slate100, border: C.border,  bg: C.surface  },
    { label: 'New Obligations in B',     items: ai.newObligationsInB || [],       color: C.amber,    border: C.amber,   bg: C.amberBg  },
    { label: 'Removed Protections in B', items: ai.removedProtectionsInB || [],   color: C.red,      border: C.red,     bg: C.redBg    },
    { label: 'Risk Decrease Factors',    items: ai.riskDecreaseFactors || [],     color: C.green,    border: C.green,   bg: C.greenBg  },
  ];

  const half = CONTENT_W / 2 - 2;
  sections.forEach((sec, i) => {
    const x    = MARGIN + (i % 2) * (half + 4);
    if (i % 2 === 0 && i > 0) y += 0; // already advanced
    const itemLines = sec.items.reduce((acc, it) => acc + doc.splitTextToSize(`• ${it}`, half - 10).length, 0);
    const boxH = Math.max(18, 12 + itemLines * 4.2);

    if (y + boxH > PAGE_H - 20) { addPage(doc); y = MARGIN; }
    doc.setFillColor(...sec.bg); doc.setDrawColor(...sec.border); doc.setLineWidth(0.3);
    doc.roundedRect(x, y, half, boxH, 2, 2, 'FD');
    set(doc, 7, 'bold', sec.color); doc.text(sec.label.toUpperCase(), x+4, y+6);
    if (sec.items.length === 0) {
      set(doc, 7.5, 'normal', C.slate500); doc.text('None identified', x+4, y+12);
    } else {
      set(doc, 8, 'normal', sec.color);
      let ty = y + 12;
      sec.items.forEach(item => {
        const lines = doc.splitTextToSize(`• ${item}`, half - 10);
        doc.text(lines, x + 4, ty);
        ty += lines.length * 4.2;
      });
    }
    if (i % 2 === 1) y += boxH + 4; // advance row after right column
  });
};

// Diff table page
const buildDiffTable = (doc, comparison) => {
  addPage(doc);
  let y = MARGIN;
  y = sectionHeading(doc, 'Clause Diff Table', y);

  const STATUS_COLORS = { added:'Added', removed:'Removed', modified:'Modified', unchanged:'Unchanged' };

  const rows = comparison.diff.map(item => [
    item.clauseType,
    STATUS_COLORS[item.status] || item.status,
    item.clauseA ? `${item.clauseA.riskLevel} (${item.clauseA.severity})` : '—',
    item.clauseB ? `${item.clauseB.riskLevel} (${item.clauseB.severity})` : '—',
    (() => {
      if (!item.clauseA || !item.clauseB) return '—';
      const d = (item.clauseB.severity || 0) - (item.clauseA.severity || 0);
      return d === 0 ? 'No change' : (d > 0 ? `+${d} riskier` : `${d} safer`);
    })(),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Clause Type', 'Status', 'A Risk (Sev)', 'B Risk (Sev)', 'Change']],
    body: rows,
    theme: 'plain',
    styles: { font:'helvetica', fontSize:8.5, textColor:C.slate100, fillColor:C.surface, lineColor:C.border, lineWidth:0.3, cellPadding:3 },
    headStyles: { fillColor:C.primaryDark, textColor:C.white, fontStyle:'bold', fontSize:8 },
    alternateRowStyles: { fillColor:C.bg },
    bodyStyles: {},
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 1) {
        const val = data.cell.raw;
        data.cell.styles.textColor =
          val === 'Added'   ? C.green :
          val === 'Removed' ? C.red   :
          val === 'Modified'? C.amber : C.slate500;
      }
      if (data.section === 'body' && data.column.index === 4) {
        const val = String(data.cell.raw);
        data.cell.styles.textColor = val.includes('riskier') ? C.red : val.includes('safer') ? C.green : C.slate500;
      }
    },
    margin: { left:MARGIN, right:MARGIN },
  });
};

// Detailed clause diff pages
const buildDetailedDiff = (doc, comparison) => {
  const changed = comparison.diff.filter(d => d.status !== 'unchanged');
  if (!changed.length) return;

  addPage(doc);
  let y = MARGIN;
  y = sectionHeading(doc, 'Detailed Clause Changes', y);

  const STATUS_LABEL = { added:'NEW IN B', removed:'REMOVED FROM B', modified:'MODIFIED' };
  const STATUS_COLOR = { added:C.green, removed:C.red, modified:C.amber };
  const STATUS_BG    = { added:C.greenBg, removed:C.redBg, modified:C.amberBg };

  changed.forEach((item) => {
    const labelColor = STATUS_COLOR[item.status] || C.slate400;
    const labelBg    = STATUS_BG[item.status]    || C.surface;

    // Estimate height
    const half = CONTENT_W / 2 - 3;
    const aText = item.clauseA ? (item.clauseA.plainEnglish || item.clauseA.explanation || '') : '';
    const bText = item.clauseB ? (item.clauseB.plainEnglish || item.clauseB.explanation || '') : '';
    const aLines = aText ? doc.splitTextToSize(aText, half - 10).length : 0;
    const bLines = bText ? doc.splitTextToSize(bText, half - 10).length : 0;
    const boxH = 28 + Math.max(aLines, bLines) * 4.2;

    if (y + boxH > PAGE_H - 20) { addPage(doc); y = MARGIN; }

    // Container card
    doc.setFillColor(...labelBg); doc.setDrawColor(...labelColor); doc.setLineWidth(0.4);
    doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 2, 2, 'FD');

    // Header
    set(doc, 7, 'bold', labelColor); doc.text(STATUS_LABEL[item.status] || item.status.toUpperCase(), MARGIN+5, y+6);
    set(doc, 10, 'bold', C.white);   doc.text(item.clauseType, MARGIN+5, y+12);

    // Two columns
    const colA = MARGIN + 5;
    const colB = MARGIN + half + 8;

    if (item.clauseA && item.clauseB) {
      // Modified — show both
      set(doc, 7, 'bold', C.slate400); doc.text('CONTRACT A', colA, y+19);
      set(doc, 7, 'bold', C.slate400); doc.text('CONTRACT B', colB, y+19);

      set(doc, 7.5, 'normal', C.red);
      const aL = doc.splitTextToSize(aText || '—', half - 10);
      doc.text(aL, colA, y+24);

      set(doc, 7.5, 'normal', C.green);
      const bL = doc.splitTextToSize(bText || '—', half - 10);
      doc.text(bL, colB, y+24);

      // Severity change pill
      if (item.clauseA.severity != null && item.clauseB.severity != null) {
        const d = item.clauseB.severity - item.clauseA.severity;
        const dc = d > 0 ? C.red : d < 0 ? C.green : C.slate400;
        set(doc, 7.5, 'bold', dc);
        doc.text(`Severity: ${item.clauseA.severity} → ${item.clauseB.severity}`, colA, y+boxH-5);
      }
    } else {
      // Added or Removed
      const clause = item.clauseA || item.clauseB;
      const text   = clause ? (clause.plainEnglish || clause.explanation || clause.clauseText || '') : '';
      set(doc, 7.5, 'normal', C.slate100);
      const lines = doc.splitTextToSize(text, CONTENT_W - 12);
      doc.text(lines, MARGIN+5, y+20);
      if (clause?.riskLevel) {
        set(doc, 7.5, 'bold', riskColor(clause.riskLevel));
        doc.text(`${clause.riskLevel} Risk — Severity ${clause.severity}/10`, MARGIN+5, y+boxH-5);
      }
    }

    y += boxH + 4;
  });
};

// ── Main export ──────────────────────────────────────────────────────────────
export const generateComparisonPDF = (comparison) => {
  const doc = new jsPDF({ orientation:'portrait', unit:'mm', format:'a4' });

  buildCover(doc, comparison);
  buildAISummary(doc, comparison);
  buildDiffTable(doc, comparison);
  buildDetailedDiff(doc, comparison);

  // Page numbers
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) { doc.setPage(i); footer(doc, i, total); }

  // Filename
  const nameA = (comparison.contractA.fileName || 'ContractA').replace(/\.[^/.]+$/,'').replace(/[^a-zA-Z0-9_\- ]/g,'').replace(/\s+/g,'_').substring(0,30);
  const nameB = (comparison.contractB.fileName || 'ContractB').replace(/\.[^/.]+$/,'').replace(/[^a-zA-Z0-9_\- ]/g,'').replace(/\s+/g,'_').substring(0,30);
  doc.save(`${nameA}_vs_${nameB}_Comparison.pdf`);
};
