import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// ─── Colour palette (RGB) ────────────────────────────────────────────────────
const C = {
  bg:         [10,  15,  30],   // near-black page background
  surface:    [18,  27,  50],   // card background
  border:     [37,  52,  85],   // subtle border
  primary:    [99, 102, 241],   // indigo-500
  primaryDark:[67,  56, 202],   // indigo-700
  white:      [255,255, 255],
  slate100:   [241,245, 249],
  slate300:   [148,163, 184],
  slate400:   [100,116, 139],
  slate500:   [71,  85, 105],
  red:        [239, 68,  68],
  redBg:      [69,  10,  10],
  amber:      [245,158,  11],
  amberBg:    [69,  39,   3],
  green:      [16, 185, 129],
  greenBg:    [6,   55,  32],
};

// ─── Typography helpers ───────────────────────────────────────────────────────
const font = {
  title:    { size: 26, style: 'bold'   },
  h1:       { size: 18, style: 'bold'   },
  h2:       { size: 13, style: 'bold'   },
  h3:       { size: 10, style: 'bold'   },
  body:     { size:  9, style: 'normal' },
  small:    { size:  7.5, style: 'normal' },
  label:    { size:  7,   style: 'bold'   },
};

const set = (doc, f, color = C.white) => {
  doc.setFontSize(f.size);
  doc.setFont('helvetica', f.style);
  doc.setTextColor(...color);
};

// ─── Layout constants ─────────────────────────────────────────────────────────
const PAGE_W  = 210;   // A4 width  mm
const PAGE_H  = 297;   // A4 height mm
const MARGIN  = 14;
const CONTENT_W = PAGE_W - MARGIN * 2;

// ─── Utility: full-page dark background ──────────────────────────────────────
const fillPage = (doc) => {
  doc.setFillColor(...C.bg);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
};

// ─── Utility: add page with background ───────────────────────────────────────
const addPage = (doc) => {
  doc.addPage();
  fillPage(doc);
};

// ─── Utility: page-number footer ─────────────────────────────────────────────
const addFooter = (doc, pageNum, totalPages) => {
  const y = PAGE_H - 8;
  set(doc, font.small, C.slate500);
  doc.text('Generated by LexAudit  |  AI-generated analysis — not legal advice', MARGIN, y);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, y, { align: 'right' });
  // footer rule
  doc.setDrawColor(...C.border);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y - 3, PAGE_W - MARGIN, y - 3);
};

// ─── Utility: section heading with accent bar ─────────────────────────────────
const sectionHeading = (doc, text, y) => {
  doc.setFillColor(...C.primary);
  doc.rect(MARGIN, y, 3, 6, 'F');
  set(doc, font.h2, C.white);
  doc.text(text, MARGIN + 6, y + 4.5);
  return y + 12;
};

// ─── Utility: risk colour ─────────────────────────────────────────────────────
const riskColor = (level) =>
  level === 'High'   ? C.red   :
  level === 'Medium' ? C.amber : C.green;

const riskBgColor = (level) =>
  level === 'High'   ? C.redBg   :
  level === 'Medium' ? C.amberBg : C.greenBg;

// ─── Utility: wrapped text block, returns new y ───────────────────────────────
const textBlock = (doc, text, x, y, maxW, lineH = 4.5) => {
  if (!text) return y;
  const lines = doc.splitTextToSize(String(text), maxW);
  doc.text(lines, x, y);
  return y + lines.length * lineH;
};

// ─── Utility: labelled field ──────────────────────────────────────────────────
const field = (doc, label, value, x, y, maxW) => {
  if (!value) return y;
  set(doc, font.label, C.slate400);
  doc.text(label.toUpperCase(), x, y);
  set(doc, font.body, C.slate100);
  return textBlock(doc, value, x, y + 4, maxW) + 2;
};

// ─── Utility: coloured pill / badge ──────────────────────────────────────────
const pill = (doc, label, x, y, color, bgColor) => {
  const w = doc.getTextWidth(label) + 6;
  doc.setFillColor(...bgColor);
  doc.roundedRect(x, y - 4, w, 6, 1.5, 1.5, 'F');
  set(doc, font.label, color);
  doc.text(label, x + 3, y);
  return w;
};

// ─── Utility: card rectangle ──────────────────────────────────────────────────
const card = (doc, x, y, w, h, fillColor = C.surface) => {
  doc.setFillColor(...fillColor);
  doc.setDrawColor(...C.border);
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, w, h, 2, 2, 'FD');
};

// ─── PAGE 1: Cover ────────────────────────────────────────────────────────────
const buildCoverPage = (doc, contract, clauses) => {
  fillPage(doc);

  // Gradient header band
  doc.setFillColor(...C.primaryDark);
  doc.rect(0, 0, PAGE_W, 70, 'F');
  doc.setFillColor(...C.primary);
  doc.rect(0, 60, PAGE_W, 12, 'F');

  // Logo wordmark
  set(doc, { size: 28, style: 'bold' }, C.white);
  doc.text('Lex', MARGIN, 32);
  set(doc, { size: 28, style: 'bold' }, [167, 170, 255]);
  doc.text('Audit', MARGIN + doc.getTextWidth('Lex'), 32);

  set(doc, font.body, [199, 210, 254]);
  doc.text('AI Contract Risk Analyzer', MARGIN, 42);

  // Report title
  set(doc, font.h1, C.white);
  doc.text('CONTRACT ANALYSIS REPORT', MARGIN, 58);

  // Contract name box
  let y = 82;
  card(doc, MARGIN, y, CONTENT_W, 22);
  set(doc, font.label, C.slate400);
  doc.text('CONTRACT', MARGIN + 6, y + 7);
  set(doc, font.h2, C.white);
  const nameLines = doc.splitTextToSize(contract.fileName || 'Untitled Contract', CONTENT_W - 12);
  doc.text(nameLines, MARGIN + 6, y + 13);
  y += 28;

  // Meta grid: Date | Status | Score
  const colW = CONTENT_W / 3;
  const metaItems = [
    { label: 'Analysis Date', value: new Date(contract.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) },
    { label: 'Total Clauses', value: `${clauses.length} identified` },
    { label: 'Analysis Status', value: contract.status === 'completed' ? 'Completed' : contract.status },
  ];
  metaItems.forEach((item, i) => {
    const x = MARGIN + i * colW;
    card(doc, x, y, colW - 2, 18, C.surface);
    set(doc, font.label, C.slate400);
    doc.text(item.label.toUpperCase(), x + 5, y + 7);
    set(doc, font.body, C.slate100);
    doc.text(item.value, x + 5, y + 13);
  });
  y += 24;

  // Risk Score hero
  card(doc, MARGIN, y, CONTENT_W, 52, C.surface);
  const score = contract.riskScore ?? 0;
  const level = contract.riskLevel ?? 'Low';
  const rc    = riskColor(level);

  set(doc, { size: 52, style: 'bold' }, rc);
  doc.text(String(score), PAGE_W / 2, y + 32, { align: 'center' });
  set(doc, font.label, C.slate400);
  doc.text('OVERALL RISK SCORE  /  100', PAGE_W / 2, y + 40, { align: 'center' });
  pill(doc, `${level.toUpperCase()} RISK`, PAGE_W / 2 - 15, y + 48, rc, riskBgColor(level));

  // Risk breakdown mini bars
  const high   = clauses.filter(c => c.riskLevel === 'High').length;
  const medium = clauses.filter(c => c.riskLevel === 'Medium').length;
  const low    = clauses.filter(c => c.riskLevel === 'Low').length;
  y += 58;

  const barItems = [
    { label: 'High Risk',   count: high,   color: C.red   },
    { label: 'Medium Risk', count: medium, color: C.amber },
    { label: 'Low Risk',    count: low,    color: C.green },
  ];
  const bw = CONTENT_W / 3;
  barItems.forEach((b, i) => {
    const x = MARGIN + i * bw;
    card(doc, x, y, bw - 2, 16, C.surface);
    set(doc, { size: 14, style: 'bold' }, b.color);
    doc.text(String(b.count), x + 7, y + 10);
    set(doc, font.small, C.slate400);
    doc.text(b.label, x + 7 + doc.getTextWidth(String(b.count)) + 3, y + 10);
  });
  y += 22;

  // Final recommendation
  const rec = contract.summary?.finalRecommendation || '—';
  const recColor = rec === 'Sign' ? C.green : rec === 'Do Not Sign' ? C.red : C.amber;
  card(doc, MARGIN, y, CONTENT_W, 16, C.surface);
  set(doc, font.label, C.slate400);
  doc.text('FINAL RECOMMENDATION', MARGIN + 5, y + 7);
  set(doc, font.h3, recColor);
  doc.text(rec.toUpperCase(), MARGIN + 5, y + 13);
  y += 20;

  // Disclaimer at bottom
  y = PAGE_H - 22;
  doc.setDrawColor(...C.border);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  set(doc, font.small, C.slate500);
  doc.text('This analysis is AI-generated and should not be considered legal advice.', MARGIN, y + 5);
  doc.text('Consult a qualified attorney before making any legal decisions.', MARGIN, y + 9);
};

// ─── PAGE 2: Executive Summary ────────────────────────────────────────────────
const buildSummaryPage = (doc, contract) => {
  addPage(doc);
  let y = MARGIN;

  y = sectionHeading(doc, 'Executive Summary', y);

  const summary = contract.summary;
  if (!summary) {
    set(doc, font.body, C.slate400);
    doc.text('No executive summary available.', MARGIN, y);
    return;
  }

  // Overview
  if (summary.overview) {
    card(doc, MARGIN, y, CONTENT_W, 2, C.surface); // dynamic height below
    set(doc, font.h3, C.primary);
    doc.text('Overview', MARGIN + 5, y + 6);
    set(doc, font.body, C.slate100);
    const lines = doc.splitTextToSize(summary.overview, CONTENT_W - 10);
    doc.text(lines, MARGIN + 5, y + 12);
    const boxH = 14 + lines.length * 4.5;
    card(doc, MARGIN, y, CONTENT_W, boxH, C.surface);
    set(doc, font.h3, C.primary);
    doc.text('Overview', MARGIN + 5, y + 6);
    set(doc, font.body, C.slate100);
    doc.text(lines, MARGIN + 5, y + 12);
    y += boxH + 5;
  }

  // Three-column grid: Top Risks | Missing Protections | Recommended Actions
  const cols = [
    { label: 'Top Risks',             items: summary.topRisks || [],            color: C.red,   bg: C.redBg   },
    { label: 'Missing Protections',   items: summary.missingProtections || [],  color: C.amber, bg: C.amberBg },
    { label: 'Recommended Actions',   items: summary.recommendedActions || [],  color: C.green, bg: C.greenBg },
  ];

  const colW = CONTENT_W / 3;
  // Compute max height needed
  let maxLines = 0;
  cols.forEach(col => {
    let lines = 0;
    col.items.forEach(item => {
      lines += doc.splitTextToSize(`• ${item}`, colW - 12).length;
    });
    if (lines > maxLines) maxLines = lines;
  });
  const gridH = Math.max(40, 12 + maxLines * 4.5 + 4);

  cols.forEach((col, i) => {
    const x = MARGIN + i * colW;
    doc.setFillColor(...col.bg);
    doc.setDrawColor(...col.color);
    doc.setLineWidth(0.4);
    doc.roundedRect(x, y, colW - 2, gridH, 2, 2, 'FD');
    set(doc, font.label, col.color);
    doc.text(col.label.toUpperCase(), x + 5, y + 7);
    set(doc, font.body, C.slate100);
    let ty = y + 13;
    col.items.forEach(item => {
      const wrapped = doc.splitTextToSize(`• ${item}`, colW - 12);
      doc.text(wrapped, x + 5, ty);
      ty += wrapped.length * 4.5;
    });
    if (!col.items.length) {
      set(doc, font.small, C.slate500);
      doc.text('None identified', x + 5, y + 13);
    }
  });
  y += gridH + 6;

  // Final recommendation highlight
  const rec = contract.summary?.finalRecommendation || '—';
  const recC  = rec === 'Sign' ? C.green : rec === 'Do Not Sign' ? C.red : C.amber;
  const recBg = rec === 'Sign' ? C.greenBg : rec === 'Do Not Sign' ? C.redBg : C.amberBg;
  doc.setFillColor(...recBg);
  doc.setDrawColor(...recC);
  doc.setLineWidth(0.5);
  doc.roundedRect(MARGIN, y, CONTENT_W, 14, 2, 2, 'FD');
  set(doc, font.label, C.slate400);
  doc.text('FINAL RECOMMENDATION', MARGIN + 5, y + 6);
  set(doc, font.h3, recC);
  doc.text(rec, MARGIN + 5, y + 12);
};

// ─── PAGE 3: Risk Dashboard ───────────────────────────────────────────────────
const buildDashboardPage = (doc, contract, clauses) => {
  addPage(doc);
  let y = MARGIN;

  y = sectionHeading(doc, 'Risk Dashboard', y);

  const high   = clauses.filter(c => c.riskLevel === 'High');
  const medium = clauses.filter(c => c.riskLevel === 'Medium');
  const low    = clauses.filter(c => c.riskLevel === 'Low');
  const score  = contract.riskScore ?? 0;

  // Score gauge (text-based, no canvas needed)
  card(doc, MARGIN, y, CONTENT_W, 36, C.surface);
  const level = contract.riskLevel ?? 'Low';
  set(doc, { size: 40, style: 'bold' }, riskColor(level));
  doc.text(String(score), MARGIN + 30, y + 24, { align: 'center' });
  set(doc, font.small, C.slate400);
  doc.text('/ 100', MARGIN + 46, y + 24);
  set(doc, font.label, C.slate400);
  doc.text('OVERALL RISK SCORE', MARGIN + 30, y + 30, { align: 'center' });

  // Score scale bar
  const barX = MARGIN + 65, barY = y + 12, barW = CONTENT_W - 70, barH = 8;
  doc.setFillColor(...C.border);
  doc.roundedRect(barX, barY, barW, barH, 2, 2, 'F');
  const fillW = Math.max(4, (score / 100) * barW);
  const fillColor = score > 60 ? C.red : score > 30 ? C.amber : C.green;
  doc.setFillColor(...fillColor);
  doc.roundedRect(barX, barY, fillW, barH, 2, 2, 'F');
  // Scale labels
  set(doc, font.small, C.green);  doc.text('0',   barX, barY + barH + 5);
  set(doc, font.small, C.amber);  doc.text('31',  barX + barW * 0.31, barY + barH + 5);
  set(doc, font.small, C.red);    doc.text('61',  barX + barW * 0.61, barY + barH + 5);
  set(doc, font.small, C.slate400); doc.text('100', barX + barW - 4, barY + barH + 5);

  // Zone labels
  set(doc, font.small, C.green);  doc.text('Low', barX + barW * 0.1,  barY - 2);
  set(doc, font.small, C.amber);  doc.text('Medium', barX + barW * 0.41, barY - 2);
  set(doc, font.small, C.red);    doc.text('High', barX + barW * 0.75, barY - 2);
  y += 42;

  // Risk breakdown cards
  const breakdown = [
    { label: 'High Risk Clauses',   count: high.length,   color: C.red,   bg: C.redBg   },
    { label: 'Medium Risk Clauses', count: medium.length, color: C.amber, bg: C.amberBg },
    { label: 'Low Risk Clauses',    count: low.length,    color: C.green, bg: C.greenBg },
    { label: 'Total Clauses',       count: clauses.length, color: C.primary, bg: C.surface },
  ];

  const bw = CONTENT_W / 4;
  breakdown.forEach((b, i) => {
    const x = MARGIN + i * bw;
    doc.setFillColor(...b.bg);
    doc.setDrawColor(...b.color);
    doc.setLineWidth(0.4);
    doc.roundedRect(x, y, bw - 2, 22, 2, 2, 'FD');
    set(doc, { size: 18, style: 'bold' }, b.color);
    doc.text(String(b.count), x + (bw / 2) - 1, y + 13, { align: 'center' });
    set(doc, font.small, C.slate400);
    doc.text(b.label, x + (bw / 2) - 1, y + 19, { align: 'center' });
  });
  y += 28;

  // Clause-type breakdown table
  y = sectionHeading(doc, 'Clause Breakdown by Type', y);

  const typeMap = {};
  clauses.forEach(c => {
    if (!typeMap[c.clauseType]) typeMap[c.clauseType] = { High: 0, Medium: 0, Low: 0 };
    typeMap[c.clauseType][c.riskLevel] = (typeMap[c.clauseType][c.riskLevel] || 0) + 1;
  });

  const tableRows = Object.entries(typeMap).map(([type, counts]) => [
    type,
    counts.High   || 0,
    counts.Medium || 0,
    counts.Low    || 0,
    Math.max(
      ...clauses.filter(c => c.clauseType === type).map(c => c.severity || 0)
    ),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Clause Type', 'High', 'Medium', 'Low', 'Max Severity']],
    body: tableRows,
    theme: 'plain',
    styles: {
      font: 'helvetica', fontSize: 8.5,
      textColor: C.slate100, fillColor: C.surface,
      lineColor: C.border, lineWidth: 0.3, cellPadding: 3,
    },
    headStyles: {
      fillColor: C.primaryDark, textColor: C.white,
      fontStyle: 'bold', fontSize: 8,
    },
    alternateRowStyles: { fillColor: C.bg },
    columnStyles: {
      1: { textColor: C.red,   halign: 'center' },
      2: { textColor: C.amber, halign: 'center' },
      3: { textColor: C.green, halign: 'center' },
      4: { textColor: C.slate300, halign: 'center' },
    },
    margin: { left: MARGIN, right: MARGIN },
  });
};

// ─── PAGE 4: Missing Critical Clauses ────────────────────────────────────────
const MISSING_CLAUSE_DESCRIPTIONS = {
  'Confidentiality Clause':
    'Protects sensitive business information from being disclosed to third parties. Without it, there is no contractual obligation for the other party to keep your information secret.',
  'Termination Clause':
    'Defines the conditions under which either party can end the agreement. Its absence may leave you with no clear exit path and potential liability for abrupt termination.',
  'Arbitration Clause':
    'Provides a cost-effective dispute resolution mechanism outside of courts. Without it, all disputes default to expensive and time-consuming litigation.',
  'Liability Clause':
    'Limits the financial exposure of each party in the event of a breach or loss. Without a liability cap, you may face unlimited financial claims.',
  'Data Privacy Clause':
    'Governs how personal data is collected, stored, and processed. Its absence may create regulatory non-compliance risks under GDPR, CCPA, or similar laws.',
  'Intellectual Property Clause':
    'Clarifies ownership of IP created during the contract. Without it, ownership disputes can arise over work product, inventions, or proprietary processes.',
  'Governing Law Clause':
    'Specifies which jurisdiction\'s laws apply to the contract. Without it, a court will decide which law governs, potentially in an unfavourable jurisdiction.',
  'Indemnification Clause':
    'Determines which party compensates the other for losses arising from specific events. Its absence may leave you liable for costs caused by the other party.',
  'Payment Terms':
    'Defines when and how payments must be made. Without clear payment terms, collecting overdue amounts becomes significantly more difficult.',
  'Non-Compete Clause':
    'Restricts competition after the contract ends. While its absence benefits the party bound by it, its presence without clear limits can be overly restrictive.',
};

const buildMissingClausesPage = (doc, missingClauses) => {
  if (!missingClauses || missingClauses.length === 0) return;
  addPage(doc);
  let y = MARGIN;

  y = sectionHeading(doc, 'Missing Critical Clauses', y);

  set(doc, font.body, C.slate300);
  const intro = 'The following standard clauses were not found in this contract. Their absence may expose you to unnecessary legal and financial risk.';
  y = textBlock(doc, intro, MARGIN, y, CONTENT_W) + 5;

  missingClauses.forEach((clauseName, idx) => {
    const desc = MISSING_CLAUSE_DESCRIPTIONS[clauseName] ||
      'This clause is typically expected in contracts of this type. Its absence may create ambiguity or legal exposure.';

    const descLines = doc.splitTextToSize(desc, CONTENT_W - 14);
    const boxH = 22 + descLines.length * 4.2;

    // Page overflow guard
    if (y + boxH > PAGE_H - 18) { addPage(doc); y = MARGIN; }

    // Warning card
    doc.setFillColor(...C.amberBg);
    doc.setDrawColor(...C.amber);
    doc.setLineWidth(0.4);
    doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 2, 2, 'FD');

    // Warning icon substitute (triangle of text)
    set(doc, { size: 9, style: 'bold' }, C.amber);
    doc.text('⚠', MARGIN + 4, y + 7);

    // Clause name
    set(doc, font.h3, C.amber);
    doc.text(`${idx + 1}. ${clauseName}`, MARGIN + 11, y + 7);

    // Description
    set(doc, font.body, C.slate100);
    doc.text(descLines, MARGIN + 7, y + 14);

    y += boxH + 4;
  });
};

// ─── PAGES 5+: Clause Analysis ───────────────────────────────────────────────
const buildClausePages = (doc, clauses) => {
  if (!clauses || clauses.length === 0) return;

  // Sort: High → Medium → Low
  const sorted = [...clauses].sort((a, b) => {
    const order = { High: 0, Medium: 1, Low: 2 };
    return (order[a.riskLevel] ?? 1) - (order[b.riskLevel] ?? 1);
  });

  sorted.forEach((clause, idx) => {
    addPage(doc);
    let y = MARGIN;

    // Page header
    set(doc, font.small, C.slate500);
    doc.text(`Clause Analysis  •  ${idx + 1} of ${sorted.length}`, MARGIN, y + 3);
    y += 8;

    // Clause type + badges row
    set(doc, font.h2, C.white);
    const typeLines = doc.splitTextToSize(clause.clauseType || 'Unknown Clause', CONTENT_W - 60);
    doc.text(typeLines, MARGIN, y + 5);

    // Badges (right-aligned)
    const rc  = riskColor(clause.riskLevel);
    const rbc = riskBgColor(clause.riskLevel);
    let bx = PAGE_W - MARGIN - 2;
    // Confidence badge
    if (clause.confidence != null) {
      const confLabel = `${clause.confidence}% confidence`;
      const cw = doc.getTextWidth(confLabel) + 6;
      bx -= cw;
      doc.setFillColor(...C.surface);
      doc.setDrawColor(...C.border);
      doc.setLineWidth(0.3);
      doc.roundedRect(bx, y, cw, 6, 1.5, 1.5, 'FD');
      set(doc, font.small, C.slate400);
      doc.text(confLabel, bx + 3, y + 4.2);
      bx -= 3;
    }
    // Severity badge
    const sevLabel = `Severity ${clause.severity || '—'}/10`;
    const sw = doc.getTextWidth(sevLabel) + 6;
    bx -= sw;
    doc.setFillColor(...rbc);
    doc.setDrawColor(...rc);
    doc.setLineWidth(0.3);
    doc.roundedRect(bx, y, sw, 6, 1.5, 1.5, 'FD');
    set(doc, font.small, rc);
    doc.text(sevLabel, bx + 3, y + 4.2);
    bx -= 3;
    // Risk level badge
    const riskLabel = `${clause.riskLevel || 'Unknown'} Risk`;
    const rw = doc.getTextWidth(riskLabel) + 8;
    bx -= rw;
    doc.setFillColor(...rbc);
    doc.setDrawColor(...rc);
    doc.setLineWidth(0.4);
    doc.roundedRect(bx, y, rw, 7, 1.5, 1.5, 'FD');
    set(doc, font.label, rc);
    doc.text(riskLabel, bx + 4, y + 5);

    y += typeLines.length * 5.5 + 4;

    // Divider
    doc.setDrawColor(...C.border);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 5;

    // Clause Text (quoted box)
    if (clause.clauseText) {
      const ctLines = doc.splitTextToSize(`"${clause.clauseText}"`, CONTENT_W - 10);
      const ctH = 10 + ctLines.length * 4.2;
      if (y + ctH < PAGE_H - 20) {
        doc.setFillColor(...C.surface);
        doc.setDrawColor(...C.border);
        doc.setLineWidth(0.3);
        doc.roundedRect(MARGIN, y, CONTENT_W, ctH, 2, 2, 'FD');
        doc.setFillColor(...C.primary);
        doc.rect(MARGIN, y, 3, ctH, 'F');
        set(doc, font.label, C.slate400);
        doc.text('CLAUSE TEXT', MARGIN + 6, y + 5);
        set(doc, { size: 8, style: 'italic' }, C.slate300);
        doc.text(ctLines, MARGIN + 6, y + 10);
        y += ctH + 4;
      }
    }

    // Helper to add a labelled text section, with page break guard
    const addSection = (label, text, color = C.slate100) => {
      if (!text) return;
      const lines = doc.splitTextToSize(String(text), CONTENT_W - 6);
      const needed = 10 + lines.length * 4.2;
      if (y + needed > PAGE_H - 18) { addPage(doc); y = MARGIN + 4; }
      set(doc, font.label, C.slate400);
      doc.text(label, MARGIN, y);
      y += 4.5;
      set(doc, font.body, color);
      doc.text(lines, MARGIN, y);
      y += lines.length * 4.2 + 4;
    };

    addSection('PLAIN ENGLISH', clause.plainEnglish, C.white);
    addSection('EXPLANATION', clause.explanation);
    addSection('SEVERITY JUSTIFICATION', clause.severityJustification, C.slate300);

    // Impact two-column
    if (clause.businessImpact || clause.legalImpact) {
      const halfW = CONTENT_W / 2 - 2;
      const biLines = clause.businessImpact ? doc.splitTextToSize(clause.businessImpact, halfW - 8) : [];
      const liLines = clause.legalImpact    ? doc.splitTextToSize(clause.legalImpact,    halfW - 8) : [];
      const impH = 10 + Math.max(biLines.length, liLines.length) * 4.2;
      if (y + impH < PAGE_H - 18) {
        // Business Impact
        doc.setFillColor(...C.amberBg);
        doc.setDrawColor(...C.amber);
        doc.setLineWidth(0.3);
        doc.roundedRect(MARGIN, y, halfW, impH, 2, 2, 'FD');
        set(doc, font.label, C.amber);
        doc.text('BUSINESS IMPACT', MARGIN + 4, y + 5);
        set(doc, font.body, C.slate100);
        doc.text(biLines, MARGIN + 4, y + 10);
        // Legal Impact
        const lx = MARGIN + halfW + 4;
        doc.setFillColor(...C.redBg);
        doc.setDrawColor(...C.red);
        doc.roundedRect(lx, y, halfW, impH, 2, 2, 'FD');
        set(doc, font.label, C.red);
        doc.text('LEGAL IMPACT', lx + 4, y + 5);
        set(doc, font.body, C.slate100);
        doc.text(liLines, lx + 4, y + 10);
        y += impH + 5;
      }
    }

    // Recommendations (only for Medium/High)
    if (clause.riskLevel !== 'Low' && clause.recommendation) {
      const rec = clause.recommendation;
      const recFields = [
        { label: 'WHY RISKY',           text: rec.whyRisky      },
        { label: 'SAFER ALTERNATIVE',   text: rec.saferAlternative },
        { label: 'SUGGESTED WORDING',   text: rec.modifiedWording  },
      ];

      recFields.forEach(({ label, text }) => {
        if (!text) return;
        const lines = doc.splitTextToSize(text, CONTENT_W - 10);
        const boxH = 10 + lines.length * 4.2;
        if (y + boxH > PAGE_H - 18) { addPage(doc); y = MARGIN + 4; }
        doc.setFillColor(...C.greenBg);
        doc.setDrawColor(...C.green);
        doc.setLineWidth(0.3);
        doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 2, 2, 'FD');
        set(doc, font.label, C.green);
        doc.text(label, MARGIN + 5, y + 5);
        set(doc, font.body, C.slate100);
        doc.text(lines, MARGIN + 5, y + 10);
        y += boxH + 3;
      });

      // Negotiation points
      if (rec.negotiationPoints?.length > 0) {
        const pts = rec.negotiationPoints.filter(Boolean);
        if (pts.length > 0) {
          set(doc, font.label, C.slate400);
          if (y + 8 > PAGE_H - 18) { addPage(doc); y = MARGIN + 4; }
          doc.text('NEGOTIATION POINTS', MARGIN, y);
          y += 5;
          pts.forEach(pt => {
            const ptLines = doc.splitTextToSize(`•  ${pt}`, CONTENT_W - 8);
            if (y + ptLines.length * 4.2 > PAGE_H - 18) { addPage(doc); y = MARGIN + 4; }
            set(doc, font.body, C.slate100);
            doc.text(ptLines, MARGIN + 3, y);
            y += ptLines.length * 4.2 + 1.5;
          });
        }
      }
    }
  });
};

// ─── Main export ──────────────────────────────────────────────────────────────
/**
 * Generate and download a full PDF analysis report.
 *
 * @param {object} contract  - contract document from API
 * @param {Array}  clauses   - clause array from API
 */
export const generatePDFReport = (contract, clauses) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Build all sections
  buildCoverPage(doc, contract, clauses);
  buildSummaryPage(doc, contract);
  buildDashboardPage(doc, contract, clauses);
  buildMissingClausesPage(doc, contract.missingClauses || []);
  buildClausePages(doc, clauses);

  // Stamp page numbers on every page (now we know total)
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  // Build filename: ContractName_Analysis_Report.pdf
  const base = (contract.fileName || 'Contract')
    .replace(/\.[^/.]+$/, '')          // remove extension
    .replace(/[^a-zA-Z0-9_\- ]/g, '') // strip special chars
    .replace(/\s+/g, '_')
    .substring(0, 60);
  const filename = `${base}_Analysis_Report.pdf`;

  doc.save(filename);
  return filename;
};
